package state

// Generated by stategen. DO NOT EDIT.

import(
	"github.com/neurotempest/mq_test/reflex/src/consumer"
	"testing"
)

type State interface {
	GetConsumerClient() consumer.Client
}

func (s *stateImpl) GetConsumerClient() consumer.Client {

	return s.consumerClient
}

type stateOption func(*stateImpl)

func NewStateForTesting(
	_ testing.TB,
	opts ...stateOption,
) State {

	var s stateImpl
	for _, opt := range opts {
		opt(&s)
	}
	return &s
}

func WithConsumerClient(consumerClient consumer.Client) stateOption {

	return func(s *stateImpl) {
		s.consumerClient = consumerClient
	}
}
