apiVersion: v1
kind: Service
metadata:
  name: consumer-api
spec:
  type: ClusterIP
  selector:
    app: consumer
  ports:
    - port: 5678
      targetPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  hostNetwork: true
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer
          image: microservice-image
          command:
            #- /bin/sh
            #- -c
            #- sleep infinity
            - /build/consumer_main
            - -db_uri=consumer:@tcp(mysql-server:3306)/consumer_db?parseTime=true
            - -producer_grpc_address=producer-api:1234
          ports:
            - containerPort: 5678
