apiVersion: v1
kind: Service
metadata:
  name: mysql-server
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  hostNetwork: true
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: examplepw
          args:
            # alpine linux uses mariadb client to access mysql which only
            # support `mysql_native_password`, so using this for now...
            - --default-authentication-plugin=mysql_native_password
          ports:
            - containerPort: 3306

