apiVersion: v1
kind: Service
metadata:
  name: producer-api
spec:
  type: ClusterIP
  selector:
    app: producer
  ports:
    - port: 1234
      targetPort: 1234
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  hostNetwork: true
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: microservice-image
          command:
            - /build/producer_main
          ports:
            - containerPort: 1234
