apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  hostNetwork: true
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: producer
          image: microservice-image
          command:
            - /build/producer_main
          ports:
            - containerPort: 1234
        - name: consumer
          image: microservice-image
          command:
            - /build/consumer_main
